name: macOS Release

on:
  workflow_dispatch:

env:
  qtVersion: "6.8.2"

jobs:
  macos_build:
    strategy:
        matrix:
          platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: prepare build environment
        run: |
          brew install ninja
          brew install glfw3
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qtVersion }}
      - name: "set QT_PREFIX"
        run: echo "QT_PREFIX=${Qt6_DIR}" >> $GITHUB_ENV
      - name: release build
        run: ./Scripts/release_macos.sh
      - id: commit
        uses: pr-mpt/actions-commit-hash@v3
      - name: Upload Tools
        uses: actions/upload-artifact@v4
        with:
          name: macos_${{ steps.commit.outputs.short }}
          path: Tools
