name: CI

on: [push]

env:
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_CACHE_MULTIARCH: "1"
  qtVersion: "6.5.1"
  cmakeVersion: "3.26.4"

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: prepare build environment
      run: |
        brew install ninja
        brew install glfw3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.qtVersion }}
    - name: "set QT_PREFIX"
      run: echo "QT_PREFIX=${Qt6_DIR}" >> $GITHUB_ENV
    - name: release build
      run: ./Scripts/release_macos.sh
    - name: Commit Hash
      uses: pr-mpt/actions-commit-hash@v2
    - name: Upload Tools
      uses: actions/upload-artifact@v3
      with:
        name: macos_${{ steps.commit.outputs.short }}
        path: Tools
      if: startsWith(github.ref, 'refs/tags/')

  win_x64_build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
#    - name: Run sccache-cache
#      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: ${{ env.cmakeVersion }}
    - name: Check cmake
      run: |
        cmake --version
        cmake -h
    - name: Install x64 Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.qtVersion }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
    - name: "set x64 QT_PREFIX"
      shell: bash
      run: |
        echo "QT_PREFIX=${Qt6_DIR}" >> $GITHUB_ENV
    - name: release x64 build
      shell: cmd
      run: Scripts\release_win.bat x64
    - name: Commit Hash
      uses: pr-mpt/actions-commit-hash@v2
    - name: Upload Tools
      uses: actions/upload-artifact@v3
      with:
        name: windows_x64_${{ steps.commit.outputs.short }}
        path: Tools
      if: startsWith(github.ref, 'refs/tags/')
