name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: "git submodule"
      run: git submodule update --init --recursive
    - name: prepare build environment
      run: |
        brew install qt
        brew install glfw3
    - name: release build
      run: ./Scripts/release_macos.sh
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: Tools

  win_build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: "git submodule"
      run: git submodule update --init --recursive
    - name: install cmake
      run: |
        curl -O https://cmake.org/files/v3.17/cmake-3.17.3-win64-x64.zip
        7z x cmake-3.17.3-win64-x64.zip -oC:\projects\deps
        move C:\projects\deps\cmake-* C:\projects\deps\cmake
        $env:Path = "C:\projects\deps\cmake\bin" + ";" + $env:Path
        cmake --version
        cmake -h
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: "set QT_PREFIX"
      run: $env:QT_PREFIX = $env:Qt5_Dir
    - name: release build
      shell: cmd
      run: Scripts\release_win.bat
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: Tools
