name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_MULTIARCH: "1"
    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: prepare build environment
      run: |
        brew install glfw3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
        cache: 'true'
    - name: "set QT_PREFIX"
      run: export QT_PREFIX="${Qt6_Dir}"
    - name: release build
      run: ./Scripts/release_macos.sh
    - name: Upload Tools
      uses: actions/upload-artifact@v3
      with:
        name: macos
        path: Tools

  win_build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_MULTIARCH: "1"
    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.26.4'
    - name: Check cmake
      run: |
        cmake --version
        cmake -h
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.1'
        cache: true
    - name: "set QT_PREFIX"
      run: $env:QT_PREFIX = $env:Qt6_Dir
    - name: release build
      shell: cmd
      run: Scripts\release_win.bat
    - name: Upload Tools
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: Tools
